<a href="https://colab.research.google.com/github/Sanket2iconic/Google-colab-files/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import array
x1=array.array("i",[1,2,3,4,5])
print(x1)
print(type(x1))

array('i', [1, 2, 3, 4, 5])
<class 'array.array'>


In [14]:
x2=array.array("f",[1.1,1.2,1.3,1.4,1.55])
print(x2)
print(type(x2))

array('f', [1.100000023841858, 1.2000000476837158, 1.2999999523162842, 1.399999976158142, 1.5499999523162842])
<class 'array.array'>


In [26]:
import array
x3=array.array("u",["a","b","c"])
print(x3)
print(type(x3))
print(id(x3))
add,len=x3.buffer_info()
print(add) #pincode / uniq id of the array
print(len) #lenghth of array
print(hex(add))
print(x3.itemsize) # a size is 4

array('u', 'abc')
<class 'array.array'>
139288660886128
139288665476944
3
0x7eaeab6d4f50
4


In [36]:
import numpy as np

In [29]:
#how to store a single element

In [39]:
arr1=np.array(100)
print(arr1)
print(type(arr1))

100
<class 'numpy.ndarray'>


In [40]:
print(arr1.ndim)

0


In [45]:
a=[1,2,3,4,5,6]
arr2=np.array(a)
print(arr2)
print(type(arr2))
print(arr2.ndim) #dimention
print(arr2.shape) #shape r*c
print(arr2.size) #size len
print(arr2.dtype) #datatype

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
(6,)
6
int64


In [46]:
#create a array using tuple of values
a=(1,2,3,4,5)
arr3=np.array(a)
print(arr3)
print(type(arr3))
print(arr3.ndim) #dimention
print(arr3.shape) #shape r*c
print(arr3.size) #size len
print(arr3.dtype) #datatype

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)
5
int64


In [47]:
b=np.array([1,2,3,4])
print(b)
print(type(b))
print(b.ndim) #dimention
print(b.shape) #shape r*c
print(b.size) #size len
print(b.dtype) #datatype

[1 2 3 4]
<class 'numpy.ndarray'>
1
(4,)
4
int64


#2D arrays

In [51]:
a=[[1,2,3],[4,5,6],[7,8,9]]
a1=np.array(a)
print(a1)
print(type(a1))
print(a1.ndim)
print(a1.shape)
print(a1.size)
print(a1.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
2
(3, 3)
9
int64


In [54]:
a=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
a1=np.array(a)
print(a1)
print(type(a1))
print(a1.ndim)
print(a1.shape)
print(a1.size)
print(a1.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
<class 'numpy.ndarray'>
2
(4, 4)
16
int64


In [56]:
arr = [1, 2, 3, 4, 5]
print(arr[2])

3


In [58]:
import array
arr = array.array('i', [1, 2, 3])
arr.append(4)
print(arr)

array('i', [1, 2, 3])


#traversal
 to iterate over an array to print all elemnts of an array

In [64]:
arr=np.array([1,2,3,4,5])
print(arr)
for i in arr:
  if i > 1:
    print(i)


[1 2 3 4 5]
2
3
4
5


In [65]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
#program to find even numbers
for i in a1:
  if i%2==0:
    print(i)

2
4
6
8
10


In [69]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
#program to find even numbers
arr1=(i for i in a1 if i % 2 == 0)
print(list(arr1))

[2, 4, 6, 8, 10]


In [73]:
a2=np.array([1,2,3,4,5,6,7,8,9,10])
#program to find even numbers
arr2=np.array([i for i in a1 if i % 2 == 0])
print(arr2)


[ 2  4  6  8 10]


#insertion
append: end of the array

* insert: at desired index
*  append: at end index



In [74]:
a3=np.array([1,2,3,4])
print(a3)

[1 2 3 4]


In [83]:
a3=np.array([1,2,3,4])
a3=np.append(a3,5)
print(a3)

[1 2 3 4 5]


In [89]:
a4=np.array([1,2,3,4])
a4=np.append(a4,[5,6,7,8,9,10])
print(a4)

[ 1  2  3  4  5  6  7  8  9 10]
