<a href="https://colab.research.google.com/github/Sanket2iconic/Google-colab-files/blob/main/Complete_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Machine learning Libraries
* Numpy
* Pandas
* Seaborn/matplotlib

# Module
It's a file which includes all class , functions and methods related to any topic which can be reused.

In [ ]:
class calculator:
  def add(self,x,y):
    return x+y
  def mul(self,x,y):
    return x*y
obj= calculator()

In [ ]:
# product of 4 and 5
obj.mul(4,5)

20

In [ ]:
obj.mul(10,5)

50

# Package / library
Packages includes multiple modules/collection of modules

# Numpy
* Numpy is one of the library used for data analysis and for mathematical computation.
* Numpy helps us in creating arrays , matrices.
* It also helps in solving complex mathematical problems such as linear algebra , fourier Transforms , matrix related problems can be solved.
* It is used to solve problems related to datascience , machine learning and aslo artificial Intelligence
* Image processing , audio , video

# What can be done with Numpy?
* create arrays to store values.
* We can generate arrays using inbuilt functions.
* Indexing and slicing
* Mathematical operations , statistical ,mathematical functions .
* Matrix multiplication , determinant , inverse , eigen values

In [ ]:
# pip is package manager used to install any libraries in python
!pip install numpy

In [ ]:
# import the libraries
import numpy as np

In [ ]:
# create an array to store 100
arr = np.array(100)
print(arr)
print("type",type(arr))
print("number of elements:",arr.size)
print("dimension:",arr.ndim)
print("data type:",arr.dtype)
print("no of rows and columns",arr.shape)

100
type <class 'numpy.ndarray'>
number of elements: 1
dimension: 0
data type: int64
no of rows and columns ()


# functions and method
* size :It is find length of an array
* type: It is used to find type of an object
* dtype: It is used to find data type of object
* shape: It gives number of rows and columns
* ndim: It is used to find dimension of an array

In [ ]:
# create an array to store values [10,20,30,40,50]
arr = np.array([10,20,30,40,50]) #np.array((10,20,30,40,50))
print(arr)
print("type",type(arr))
print("number of elements:",arr.size)
print("dimension:",arr.ndim)
print("data type:",arr.dtype)
print("no of rows and columns",arr.shape) # 1 row and  5 columns

[10 20 30 40 50]
type <class 'numpy.ndarray'>
number of elements: 5
dimension: 1
data type: int64
no of rows and columns (5,)


In [ ]:
'''
[1,2,3]
[4,5,6]
[7,8,9]'''
A =[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(A)
print(arr)
print("type",type(arr))
print("number of elements:",arr.size)
print("dimension:",arr.ndim)
print("data type:",arr.dtype)
print("no of rows and columns",arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
type <class 'numpy.ndarray'>
number of elements: 9
dimension: 2
data type: int64
no of rows and columns (3, 3)


In [ ]:
'''
[1,2,3]
[4,5,6]
[7,8,9]'''
A =[[[1,2,3],[4,5,6],[7,8,9]]]
arr=np.array(A)
print(arr)
print("type",type(arr))
print("number of elements:",arr.size)
print("dimension:",arr.ndim)
print("data type:",arr.dtype)
print("no of rows and columns",arr.shape)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
type <class 'numpy.ndarray'>
number of elements: 9
dimension: 3
data type: int64
no of rows and columns (1, 3, 3)


In [ ]:
# (1,3,3): 3*3 matrix along x -axis
# (2,3,3): 3*3 matrix along x and y_axis
# (3,3,3): #*3 matrix along x,y,z axis

In [ ]:
# size = no_of_rows * no_of_columns

# Numpy math functions
* sum(): Sum of array elements.
* mean(): Mean of array elements.
* median(): Median of array elements.
* std(): Standard deviation of array elements.
* min(): Minimum value in an array.
* max(): Maximum value in an array.

In [ ]:
arr = np.array([10,20,30,40,50,60])
print("sum:",np.sum(arr))
print("min:",np.min(arr))
print("max:",np.max(arr))
print("mean:",np.mean(arr))
print("median",np.median(arr))
print("std",np.std(arr))# standard deviation

sum: 210
min: 10
max: 60
mean: 35.0
median 35.0
std 17.07825127659933


# Inbuilt functions to generate an array

# arange():
 This function is used to create an array with evenly spaced values within a specified range. It takes three arguments: start, stop, and step.

In [ ]:
# generate an array which has values 1 to 100
arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
# generate array which has 0 to 10 values
arr = np.arange(11) # end value is not included
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# generate array which even numbers from 2 to 40
arr_1 = np.arange(2,41,2)
arr_1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [ ]:
# generate an array with first 10 multiples of 5
arr_2=np.arange(5,51,5)
arr_2

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

# reshape
It is used to convert lower dimension array to higher dimension

In [ ]:
# generate an array of order 3 * 3 using arange
# 3*3 =9
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# generate 7 *2 matrix  using arange
# 7*2=14 elements
arr = np.arange(1,15).reshape(7,2)
arr


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [ ]:
# generate 2d array
#len(arr)=22
# order= 11*2 , 2*11, 22*1
arr = np.arange(22).reshape(11,2)
arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [ ]:
# generate an 2d array using 2,4,6,8,10,12,14,16,18,20
# 10= 2* 5 , 5* 2, 10*1
arr = np.arange(2,21,2).reshape(2,5)
arr

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [ ]:
# generate a 3d array of order (1,2,3)
# elements = 6
arr = np.arange(1,7).reshape(1,2,3)
arr

array([[[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
# generate 3d array of order (3,2,2)
# elements= 3* 2*2=12
arr=np.arange(10,22).reshape(3,2,2)
arr

array([[[10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21]]])

In [ ]:
arr.size

12

In [ ]:
# generate 3d array of any order for given data 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
# elements = 15
# 15 = 1 * 3*5
arr = np.arange(1,16).reshape(1,3,5)
arr

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [ ]:
# generate 3d array using 18 elements
arr = np.arange(1,19).reshape(2,3,3)
print(arr)
print(arr.ndim)
print(arr.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
3
(2, 3, 3)


In [ ]:
np.array(1)


array(1)

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [ ]:
np.array([[[1,2],[3,4]]])

array([[[1, 2],
        [3, 4]]])

# linspace
It is used to generate equal spaced values between given range/interval.

In [ ]:
# generate equal spaced values between 1 and 10
arr = np.linspace(1,1000) #by default it gives 50 equal space
arr

array([   1.        ,   21.3877551 ,   41.7755102 ,   62.16326531,
         82.55102041,  102.93877551,  123.32653061,  143.71428571,
        164.10204082,  184.48979592,  204.87755102,  225.26530612,
        245.65306122,  266.04081633,  286.42857143,  306.81632653,
        327.20408163,  347.59183673,  367.97959184,  388.36734694,
        408.75510204,  429.14285714,  449.53061224,  469.91836735,
        490.30612245,  510.69387755,  531.08163265,  551.46938776,
        571.85714286,  592.24489796,  612.63265306,  633.02040816,
        653.40816327,  673.79591837,  694.18367347,  714.57142857,
        734.95918367,  755.34693878,  775.73469388,  796.12244898,
        816.51020408,  836.89795918,  857.28571429,  877.67346939,
        898.06122449,  918.44897959,  938.83673469,  959.2244898 ,
        979.6122449 , 1000.        ])

In [ ]:
# generate an array which includes 20 equal spacing values between 1 to 100
arr = np.linspace(1,100,20,retstep=True)
arr
# retstep: It gives common difference

(array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
         21.84210526,  27.05263158,  32.26315789,  37.47368421,
         42.68421053,  47.89473684,  53.10526316,  58.31578947,
         63.52631579,  68.73684211,  73.94736842,  79.15789474,
         84.36842105,  89.57894737,  94.78947368, 100.        ]),
 5.2105263157894735)

In [ ]:
# generate 5 equal spacing values between o to 100
arr = np.linspace(0,100,5,retstep=True)
arr

(array([  0.,  25.,  50.,  75., 100.]), 25.0)

# Random functions
* randint
* randn
* rand

#randint :
 It is used to generate an array with random integers between given range

In [ ]:
# generate random integer between 1 to 100
arr = np.random.randint(1,100)
arr

37

In [ ]:
# generate 10 random integers between 1 to 1000
arr=np.random.randint(1,1000,10)
arr

array([166, 488, 461,  18, 645, 183, 957, 944, 927,  25])

# randn :
It is used to generate normal distribution values between -3 to 3

In [ ]:
arr = np.random.randn(100)
arr

array([-2.71270415,  0.54249146,  0.76306611, -0.57946513, -1.25213671,
       -0.82314148,  0.86227034,  1.42107018,  1.10113222,  1.46158977,
       -1.02387136, -0.40288743, -0.6168541 ,  1.45192093, -0.71673696,
       -2.38777997,  0.75142014, -0.08461865, -0.32846874,  0.34981913,
        1.09704448, -0.25859346, -0.2960993 ,  1.19895118,  0.10600659,
       -1.53005954,  0.49136133, -0.69902158,  0.98797898,  0.39918483,
        0.52607778,  0.18330136, -0.63473503,  0.94546671, -0.93560866,
       -0.08249049, -0.74238554,  0.34879803,  0.24025111,  0.72038204,
        0.18785362, -0.69405777,  0.6049057 , -0.36262811,  0.06297257,
       -0.9998177 , -0.4694622 , -1.44652878,  1.1981236 ,  0.73959953,
        1.31073919,  0.60242438,  0.62502266, -1.66605097, -0.61638568,
        1.45978095, -0.95703664,  1.51878762,  1.39222477,  2.35216937,
       -0.06369166, -0.05387829, -0.72862132, -0.77116155,  0.4112432 ,
        0.99288437,  0.83467271, -0.78754562, -0.94333806,  0.68

# rand
It is used to generate values between 0 and 1

In [ ]:
arr = np.random.rand(5)
arr

array([0.84084658, 0.3643287 , 0.83664772, 0.58399091, 0.84675638])

# transpose
It is used to convert rows and columns and vice versa.

In [ ]:
'''
[1,2]
[3,4]'''
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [ ]:
np.transpose(arr)

array([[1, 3],
       [2, 4]])

# flatten
It is used to convert higher dimensional array into lower dimesional

In [ ]:
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [ ]:
# convert 2d array to 1d array
arr.flatten()

array([1, 2, 3, 4])

# sort
It is used to sort in either increasing or decreasing order

In [ ]:
arr =np.array([1000,2,3000,45,67,890,3,25])
np.sort(arr) #increasing order

array([   2,    3,   25,   45,   67,  890, 1000, 3000])

In [ ]:
np.sort(arr)[::-1]#decreasing order

array([3000, 1000,  890,   67,   45,   25,    3,    2])

# concatenate array


In [ ]:
A=np.arange(1,5)
B=np.arange(10,15)

In [ ]:
# combine 2 arrays
np.concatenate((A,B))

array([ 1,  2,  3,  4, 10, 11, 12, 13, 14])

# Indexing and slicing

In [ ]:
arr = np.array([10,20,30,40,50,60,70])


In [ ]:
# fetch 20
arr[1]

20

In [ ]:
# fetch 70
arr[-1]

70

In [ ]:
# fetch 20,30,40
arr[1:4]

array([20, 30, 40])

# 2d arrays

In [ ]:
'''
[1,2,3]
[4,5,6]
[7,8,9]'''
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
# fetch first row
arr[0]

array([1, 2, 3])

In [ ]:
# fetch last row
arr[2]

array([7, 8, 9])

In [ ]:
# fetch 1st and 2nd row
arr[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# fetch 1st and 3rd row
arr[0::2]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
arr[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# fetch 1st column
arr[:,[0]]

array([[1],
       [4],
       [7]])

In [ ]:
# fetch 3rd column
arr[:,[2]]

array([[3],
       [6],
       [9]])

In [ ]:
# fetch 1st and 2nd column
arr[: , 0:2] #arr[:,[0,1]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
arr[:,[0,1]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
#fetch 2nd and 3rd column
arr[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
arr[:,[1,2]]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# fetch
'''
[1 2]
[3 4]'''
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [ ]:
'''
[2 3]
[5 6]'''
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# fetch 5
arr[1,1]

5

In [ ]:
# fetch 3
arr[0,2]

3



---



---



---



---



---



In [ ]:
#numpy data types:
import numpy as np

  * i for integer
  * u for unsigned integer
  * b for bollean
  * f for float
  * for complex fload
  * m for timedelta
  * M for timedate
  *O for object
  * S for string
  *U for unicode strings
  *V for memo



In [ ]:
# creating data types of numoy array
s=np.array([1,2,3,4])
print(s)
print(s.dtype)

[1 2 3 4]
int64


In [ ]:
s=np.array([1,2,3,4], dtype='S')
print(s)
print(s.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [ ]:
#now will create an array with datatype of 4byte int
a=np.array([1,2,3,4],dtype='i4')
print(a)
print(a.dtype)

[1 2 3 4]
int32


In [ ]:
# can not be converted then it will give value error
b=np.array(['apple','banna'],dtype='i')
print(b)
print(b.dtype)

ValueError: invalid literal for int() with base 10: 'apple'

In [ ]:
#converting datatype on existing array
#astype() function
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
#from integer to boolen
arr=np.array([1,0,3])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool




---



---



# array copy vs view
view will accept the changes in original

In [ ]:
# we will make a copy
#chnage in original array and display both
a=np.array([1,2,3,4,5])
x=a.copy() # making copy
print(a)
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
a[0]=42
print(a)
print(x) # no changes in copy

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
b=np.array([1,2,3,4,5])
y=b.view()
print(b)
print(y)

In [ ]:
b[0]=42
print(b)
print(y) #changes in the view arrayt also

[42  2  3  4  5]
[42  2  3  4  5]




---



---



---



---



#Numpy array shape

shape of an array is the number of element in each dimenssion

In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.shape)

(2, 4)


In [ ]:
# 2 is the dimenssion and 4 is the number of element in each dimention

In [ ]:
b=np.array([1,2,3,4],ndmin=5) # changing dimension
print(b)
print('shape of array:',b.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [ ]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)
print(c.ndim)#dimension of array
print(c.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)




---



---

#Array reshaping

In [ ]:
#adding and removing element
#reshaping from 1-d to 2-d

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=a.reshape(4,3)
print(a)
print(a.ndim)
print(newarr)
print(newarr.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2


In [ ]:
#from 1d to 3d
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=a.reshape(2,3,2)
print(newarr)
print(newarr.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [ ]:
#unknown dimension- we are allowed to have 1 unknown dimension
a=np.array([1,2,3,4,5,6,7,8])
newarr=a.reshape(2,2,-1)
print(newarr)
print(newarr.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


#flatning

In [ ]:
#flatning the array by converting 2d in to 1d using unknown
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
newarr=c.reshape(-1)
print(newarr)
print(newarr.ndim)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


\

---



---



---



---



#Itering arrayy-

going to element in array step by step
like loops

In [ ]:
#for 1d array

In [ ]:
a=np.array([1,2,3])
for i in a:
  print(i)

1
2
3


In [ ]:
#for 2d array
b=np.array([[1,2,3],[4,5,6]])
for i in b:
  print(i)

[1 2 3]
[4 5 6]


In [ ]:
#Scallar element of the 2D
b=np.array([[1,2,3],[4,5,6]])
for i in b:
  for j in i:
    print(j)

1
2
3
4
5
6


In [ ]:
# for 3d array
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in c:
  print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in c:
  for j in i:
    for k in j:
      print(k)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# By using the function
for i in np.nditer(c):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
#now we will iterate with different step size
a=np.array([[1,2,3,4],[5,6,7,8]])
for i in np.nditer(a[:,::3]):
  print(i)

1
4
5
8


\

---



---



---



---



#Array joining by *numpy*

In [ ]:
## here for this we will pass concatinate

In [ ]:
#joining 2 1d arrays
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b)) #using concatinate
print(c)

[1 2 3 4 5 6]


In [ ]:
#joining 2 2d arrays
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate((a,b),axis=1)
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
#joining the array using stack function
a=np.array([1,2,3])
b=np.array([4,5,6])
d=np.stack((a,b),axis=1)
print(d)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
#stacking along with rows : hstack()
a=np.array([1,2,3])
b=np.array([4,5,6])
d=np.hstack((a,b))
print(d)

[1 2 3 4 5 6]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
d=np.hstack((a,b))
print(d)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
d=np.vstack((a,b))
print(d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
d=np.vstack((a,b))
print(d)

[[1 2 3]
 [4 5 6]]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
d=np.dstack((a,b))
print(d)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


\

---



---



---



---



---

\\
#Array Spliting by *numpy*

In [ ]:
#split the array in 3 parts
#auto cutting of the arrays
a=np.array([1,2,3,4,5,6])
b=np.array_split(a,3)
print(b)
print(b[0])
print(b[1])
print(b[2])
#

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [ ]:
#spliting the 2d array
a=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
b=np.array_split(a,3)
print(a)
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [ ]:
# spliting the 2d array in 2 parts
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
b=np.array_split(a,3,axis=1)
print(a)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


\\

---


---



---

\\
#searching in array

by using where()
will give iundex where it is present

In [ ]:
a=np.array([1,2,3,4,5,4,4])
x=np.where(a==4)
print(x)
print(np.where(a==4))

(array([3, 5, 6]),)
(array([3, 5, 6]),)


In [ ]:
#finding event
a=np.array([1,2,3,4,5,6,7,8])
x=np.where(a%2==0)
print(x)
print(a[x])

(array([1, 3, 5, 7]),)
[2 4 6 8]


In [ ]:
#searchsorted()

In [ ]:
a=np.array([6,7,8,9])
x=np.searchsorted(a,7)
x1=np.where(a==7)
print(x1)
print(x)

(array([1]),)
1


In [ ]:
#now we willl search from right side

In [ ]:
x3=np.searchsorted(a,7,side='right')
print(x3)

2


In [ ]:
#search multiple values

In [ ]:
a=np.array([1,3,5,7])
x4=np.searchsorted(a,[2,4,6,8])
print(a)
print(x4)

[1 3 5 7]
[1 2 3 4]


\\

---



---



---



---

\\

---

#sorting the array
sort()

In [3]:
import numpy as np
a=np.array([3,2,0,1])
print(np.sort(a)) # like the copy method

[0 1 2 3]


In [4]:
b=np.array(['banana','cherry','apple'])
print(np.sort(b)) # sort apl

['apple' 'banana' 'cherry']


In [6]:
#sort bool
c=np.array([True,False,True])
print(np.sort(c))

[False  True  True]


In [5]:
c=np.array([[3,2,4],[5,0,1]])
print(np.sort(c))

[[2 3 4]
 [0 1 5]]


In [7]:
d=np.array([41,42,43,44])
e=np.array([46,47,48,49])
f=np.concatenate((d,e))
print(np.sort(f))

[41 42 43 44 46 47 48 49]


\

---



---



---



---

\
#filter array


In [9]:
#gettting some elements out of existing array and creating a new array
a=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=a[x]
print(newarr)

[41 43]


In [18]:
#creating the filter array
a=np.array([41,42,43,44])
filter_arr=[]
for i in a:
  if i>42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
print(filter_arr)

[False, False, True, True]


In [19]:
b=np.array([1,2,3,4,5,6,7])
filter_arr=[]
for i in b:
  if i%2==0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
print(filter_arr)

[False, True, False, True, False, True, False]
