<a href="https://colab.research.google.com/github/Sanket2iconic/Google-colab-files/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Machine learning Libraries
*Numpy

*Pandas

*Seaborn/matplotlib

#Module
its a file which includes all the class, function and method related to topic wich can be used

eg.

1)

#Package / Library

Package/Library is contain number of modules and clases


#Numpy



*  Used for data analysis and mathematical computation
* helps to create arrays and matrices
* helps to  solve complex mathematical problem (linear algebra, fourier transform, matrix)



In [2]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
a=np.array(100)
print(a)
print("type",type(a))
print("data type",a.dtype)
print("shape ( no of rows and column)",a.shape)
print("size",a.size)
print("dimension",a.ndim)


100
type <class 'numpy.ndarray'>
data type int64
shape ( no of rows and column) ()
size 1
dimension 0


In [1]:
# we can pass list, tuple or array like object. It will converted to ndarray
#0D -scalar

In [11]:
y=np.array((1,2,3,4,5))
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [12]:
# Lets make 0D array
x=np.array(42)
print(x)
print(type(x))
print(x.ndim)

42
<class 'numpy.ndarray'>
0


In [15]:
#lets make 1D array (Unidirectional arrays) consist 0D array
a=np.array([1,2,2,3,4,5])
print(a)
print(type(a))
print(a.ndim)

[1 2 2 3 4 5]
<class 'numpy.ndarray'>
1


In [19]:
#lets make 2d array - conntain two 1d array
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(type(b))
print(b.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [21]:
#lets make 3d array contain two 2D arrays
a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a)
print(type(a))
print(a.ndim) #check how many dimentionas array has

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
3


In [26]:
#lets make 4d array
aa = np.array([[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]], [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]])
print(aa)
print(type(aa))
print(aa.ndim)


[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]


 [[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]
<class 'numpy.ndarray'>
4


In [33]:
a=np.array([1,2,3,4,5],ndmin=5)
print(a)

[[[[[1 2 3 4 5]]]]]


#array indexing