In [ ]:
import array
x1=array.array("i",[1,2,3,4,5])
print(x1)
print(type(x1))

array('i', [1, 2, 3, 4, 5])
<class 'array.array'>


In [ ]:
x2=array.array("f",[1.1,1.2,1.3,1.4,1.55])
print(x2)
print(type(x2))

array('f', [1.100000023841858, 1.2000000476837158, 1.2999999523162842, 1.399999976158142, 1.5499999523162842])
<class 'array.array'>


In [ ]:
import array
x3=array.array("u",["a","b","c"])
print(x3)
print(type(x3))
print(id(x3))
add,len=x3.buffer_info()
print(add) #pincode / uniq id of the array
print(len) #lenghth of array
print(hex(add))
print(x3.itemsize) # a size is 4

array('u', 'abc')
<class 'array.array'>
139288660886128
139288665476944
3
0x7eaeab6d4f50
4


In [1]:
import numpy as np

In [ ]:
#how to store a single element

In [ ]:
arr1=np.array(100)
print(arr1)
print(type(arr1))

100
<class 'numpy.ndarray'>


In [ ]:
print(arr1.ndim)

0


In [ ]:
a=[1,2,3,4,5,6]
arr2=np.array(a)
print(arr2)
print(type(arr2))
print(arr2.ndim) #dimention
print(arr2.shape) #shape r*c
print(arr2.size) #size len
print(arr2.dtype) #datatype

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
(6,)
6
int64


In [ ]:
#create a array using tuple of values
a=(1,2,3,4,5)
arr3=np.array(a)
print(arr3)
print(type(arr3))
print(arr3.ndim) #dimention
print(arr3.shape) #shape r*c
print(arr3.size) #size len
print(arr3.dtype) #datatype

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)
5
int64


In [ ]:
b=np.array([1,2,3,4])
print(b)
print(type(b))
print(b.ndim) #dimention
print(b.shape) #shape r*c
print(b.size) #size len
print(b.dtype) #datatype

[1 2 3 4]
<class 'numpy.ndarray'>
1
(4,)
4
int64


#2D arrays

In [ ]:
a=[[1,2,3],[4,5,6],[7,8,9]]
a1=np.array(a)
print(a1)
print(type(a1))
print(a1.ndim)
print(a1.shape)
print(a1.size)
print(a1.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
2
(3, 3)
9
int64


In [ ]:
a=[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
a1=np.array(a)
print(a1)
print(type(a1))
print(a1.ndim)
print(a1.shape)
print(a1.size)
print(a1.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
<class 'numpy.ndarray'>
2
(4, 4)
16
int64


In [ ]:
arr = [1, 2, 3, 4, 5]
print(arr[2])

3


In [ ]:
import array
arr = array.array('i', [1, 2, 3])
arr.append(4)
print(arr)

array('i', [1, 2, 3])


#traversal
 to iterate over an array to print all elemnts of an array

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
for i in arr:
  if i > 1:
    print(i)


[1 2 3 4 5]
2
3
4
5


In [ ]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
#program to find even numbers
for i in a1:
  if i%2==0:
    print(i)

2
4
6
8
10


In [ ]:
a1=np.array([1,2,3,4,5,6,7,8,9,10])
#program to find even numbers
arr1=(i for i in a1 if i % 2 == 0)
print(list(arr1))

[2, 4, 6, 8, 10]


In [ ]:
a2=np.array([1,2,3,4,5,6,7,8,9,10])
#program to find even numbers
arr2=np.array([i for i in a1 if i % 2 == 0])
print(arr2)


[ 2  4  6  8 10]


#insertion
append: end of the array

* insert: at desired index
*  append: at end index

#append



In [ ]:
a3=np.array([1,2,3,4])
print(a3)

[1 2 3 4]


In [ ]:
a3=np.array([1,2,3,4])
a3=np.append(a3,5)
print(a3)

[1 2 3 4 5]


In [ ]:
a4=np.array([1,2,3,4])
a4=np.append(a4,[5,6,7,8,9,10])
print(a4)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
a5=np.array([1,2,3,4])
a6=np.array([5,6,7,8,9,10])
a5=np.append(a5,a6)
print(a5)

[ 1  2  3  4  5  6  7  8  9 10]


#insert
#np.insert(arr,index,value)

In [2]:
a7=np.array([1,2,3,5,6,7,8,9,10])
a7=np.insert(a7,3,4)
print(a7)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
b=np.array(['a','b','c','d'])
b=np.insert(b,-1,'e')
print(b)

['a' 'b' 'c' 'e' 'd']


In [4]:
print(a7)

[ 1  2  3  4  5  6  7  8  9 10]


In [5]:
a7[0]=0 # replace the values
print(a7)

[ 0  2  3  4  5  6  7  8  9 10]


In [6]:
print(a7)

[ 0  2  3  4  5  6  7  8  9 10]


#replace

In [8]:
a7[0]=1 # add at perticular index
print(a7)

[ 1  2  3  4  5  6  7  8  9 10]


#sorting
#arange in incrsing or decreasing order

In [ ]:
b=np.array([5,1,2,3,9,6,4,8,7])
b=np.sort(b)
print(b)

[1 2 3 4 5 6 7 8 9]


In [ ]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b_r=np.sort(b)[::-1]
print(b_r)

[9 8 7 6 5 4 3 2 1]


#Deletion


In [9]:
print(b)

['a' 'b' 'c' 'e' 'd']


In [10]:
b=np.delete(b,0)
print(b)

['b' 'c' 'e' 'd']


In [11]:
b=np.insert(b,0,1)
print(b)

['1' 'b' 'c' 'e' 'd']


In [12]:
b=np.delete(b,[0,1])
print(b)

['c' 'e' 'd']


In [14]:
b=np.insert(b,[0,1],['a','b'])
b=np.sort(b)
print(b)

['a' 'b' 'c' 'd' 'e']


In [20]:
b=np.delete(b,[0,-1])
print(b)

['a' 'b' 'c' 'd' 'e']


In [21]:
b=np.insert(b,[0,-1],['a','e'])
print(b)

['a' 'a' 'b' 'c' 'd' 'e' 'e']


In [22]:
b=np.delete(b,[0,-1])
print(b)

['a' 'b' 'c' 'd' 'e']


In [29]:
mask=b != 'e'
b_mask=b[mask]
print(b_mask)



['a' 'b' 'c' 'd']


#searching
#using membership operator
#in or not in

In [30]:
print(b)

['a' 'b' 'c' 'd' 'e']


In [31]:
'a'in b

True

In [54]:
b=np.array(['a','b','c','d','e','f','a'])
value=input('please enter the value you want to search ',)
if value in b:
  print('yes','at index',(np.where(b==value)[0]))
else:
  print('not present in the data')

please enter the value you want to search v
not present in the data


In [55]:
import numpy as np

b = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'a'])

try:
    while True:
        value = input('Please enter the value you want to search (or type "exit" to quit): ')
        if value.lower() == 'exit':
            print("Exiting the program.")
            raise SystemExit
        if value in b:
            print('yes, at index', np.where(b == value)[0])
        else:
            print('not present in the data')
except SystemExit:
    pass


Please enter the value you want to search (or type "exit" to quit): m
not present in the data
Please enter the value you want to search (or type "exit" to quit): exit
Exiting the program.
